// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure of table api for DAO operations like Where/Data.
type Api struct {
	g.Meta     `orm:"table:api, do:true"`
	Id         interface{} //
	Name       interface{} // 名称
	Describe   interface{} // 描述
	Type       interface{} // 请求类型
	Uri        interface{} // ip地址
	Path       interface{} // 路径
	Body       interface{} // 请求体
	State      interface{} // 状态
	CreateAt   *gtime.Time // 创建时间
	CreateUser interface{} // 创建人
	UpdateAt   *gtime.Time // 更新时间
	UpdateUser interface{} // 更新人
}
