// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Case is the golang structure of table case for DAO operations like Where/Data.
type Case struct {
	g.Meta        `orm:"table:case, do:true"`
	Id            interface{} //
	Name          interface{} // 名称
	Describe      interface{} // 描述
	State         interface{} // 状态
	CreateAt      *gtime.Time // 创建时间
	CreateUser    interface{} // 创建人
	UpdateAt      *gtime.Time // 更新时间
	UpdateUser    interface{} // 更新人
	DatabaseId    interface{} // 数据库信息
	EnvironmentId interface{} // 环境信息
}
