// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Database is the golang structure of table database for DAO operations like Where/Data.
type Database struct {
	g.Meta     `orm:"table:database, do:true"`
	Id         interface{} //
	Name       interface{} // 名称
	Describe   interface{} // 描述
	Host       interface{} // 地址
	User       interface{} // 用户
	Password   interface{} // 密码
	Database   interface{} // 数据库名
	State      interface{} // 状态
	Remarks    interface{} // 备注
	CreateAt   *gtime.Time // 创建时间
	CreateUser interface{} // 创建人
	UpdateAt   *gtime.Time // 更新时间
	UpdateUser interface{} // 更新人
}
