// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Environment is the golang structure of table environment for DAO operations like Where/Data.
type Environment struct {
	g.Meta     `orm:"table:environment, do:true"`
	Id         interface{} //
	Name       interface{} // 名称
	Describe   interface{} // 描述
	Uri        interface{} // 环境地址
	State      interface{} // 状态
	Remarks    interface{} // 备注
	CreateAt   *gtime.Time // 创建时间
	CreateUser interface{} // 创建人
	UpdateAt   *gtime.Time // 更新时间
	UpdateUser interface{} // 更新人
}
