// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserInfo is the golang structure of table user_info for DAO operations like Where/Data.
type UserInfo struct {
	g.Meta   `orm:"table:user_info, do:true"`
	Id       interface{} // User ID
	UserName interface{} // 账号
	NickName interface{} // 密码
	Password interface{} // 昵称
	Role     interface{} //
	CreateAt *gtime.Time //
	UpdateAt *gtime.Time //
}
