# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      link: "mysql:study_golang:Djc5FcebBWCjpcwJ@tcp(106.55.186.222:3306)/study_golang"
      jsonCase: "CamelLower"

  build:
    name: "my-app"
    arch: "amd64"
    system: "linux,windows,darwin"
    mod: "none"
    cgo: 0
    packSrc: "manifest/config"
    version: "1.1"
    output: "./bin"
    extra: ""