// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"myapp/internal/model"
)

type (
	IUser interface {
		Register(ctx context.Context, in model.UserRegisterInput) error
		Update(ctx context.Context, in model.UserUpdateInput) error
		Delete(ctx context.Context) error
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
