// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/dao/internal"
)

// internalDatabaseDao is internal type for wrapping internal DAO implements.
type internalDatabaseDao = *internal.DatabaseDao

// databaseDao is the data access object for table database.
// You can define custom methods on it to extend its functionality as you wish.
type databaseDao struct {
	internalDatabaseDao
}

var (
	// Database is globally public accessible object for table database operations.
	Database = databaseDao{
		internal.NewDatabaseDao(),
	}
)

// Fill with you ideas below.
