// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"myapp/internal/dao/internal"
)

// internalEnvironmentDao is internal type for wrapping internal DAO implements.
type internalEnvironmentDao = *internal.EnvironmentDao

// environmentDao is the data access object for table environment.
// You can define custom methods on it to extend its functionality as you wish.
type environmentDao struct {
	internalEnvironmentDao
}

var (
	// Environment is globally public accessible object for table environment operations.
	Environment = environmentDao{
		internal.NewEnvironmentDao(),
	}
)

// Fill with you ideas below.
