// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure for table api.
type Api struct {
	Id         int         `json:"id"         ` //
	Name       string      `json:"name"       ` // 名称
	Describe   string      `json:"describe"   ` // 描述
	Type       string      `json:"type"       ` // 请求类型
	Uri        string      `json:"uri"        ` // ip地址
	Path       string      `json:"path"       ` // 路径
	Body       string      `json:"body"       ` // 请求体
	State      int         `json:"state"      ` // 状态
	CreateAt   *gtime.Time `json:"createAt"   ` // 创建时间
	CreateUser string      `json:"createUser" ` // 创建人
	UpdateAt   *gtime.Time `json:"updateAt"   ` // 更新时间
	UpdateUser string      `json:"updateUser" ` // 更新人
}
