// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Case is the golang structure for table case.
type Case struct {
	Id            int         `json:"id"            ` //
	Name          string      `json:"name"          ` // 名称
	Describe      string      `json:"describe"      ` // 描述
	State         int         `json:"state"         ` // 状态
	CreateAt      *gtime.Time `json:"createAt"      ` // 创建时间
	CreateUser    string      `json:"createUser"    ` // 创建人
	UpdateAt      *gtime.Time `json:"updateAt"      ` // 更新时间
	UpdateUser    string      `json:"updateUser"    ` // 更新人
	DatabaseId    int         `json:"databaseId"    ` // 数据库信息
	EnvironmentId int         `json:"environmentId" ` // 环境信息
}
