// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Database is the golang structure for table database.
type Database struct {
	Id         int         `json:"id"         ` //
	Name       string      `json:"name"       ` // 名称
	Describe   string      `json:"describe"   ` // 描述
	Host       string      `json:"host"       ` // 地址
	User       string      `json:"user"       ` // 用户
	Password   string      `json:"password"   ` // 密码
	Database   string      `json:"database"   ` // 数据库名
	State      int         `json:"state"      ` // 状态
	Remarks    string      `json:"remarks"    ` // 备注
	CreateAt   *gtime.Time `json:"createAt"   ` // 创建时间
	CreateUser string      `json:"createUser" ` // 创建人
	UpdateAt   *gtime.Time `json:"updateAt"   ` // 更新时间
	UpdateUser string      `json:"updateUser" ` // 更新人
}
