// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	Id       uint        `json:"id"       ` // User ID
	UserName string      `json:"userName" ` // 账号
	NickName string      `json:"nickName" ` // 密码
	Password string      `json:"password" ` // 昵称
	Role     string      `json:"role"     ` //
	CreateAt *gtime.Time `json:"createAt" ` //
	UpdateAt *gtime.Time `json:"updateAt" ` //
}
