// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserInfo is the golang structure for table user_info.
type UserInfo struct {
	Id        int64       `json:"id"        ` //
	UserName  string      `json:"userName"  ` //
	NickName  string      `json:"nickName"  ` //
	Password  string      `json:"password"  ` //
	Role      string      `json:"role"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
